### ISSUE TITLE
Missing `-r` parameter in rostopic pub examples for cmd_vel

### ISSUE THREAD

**Issue by ghost** [clearpathrobotics/cpr-documentation#194]
It seems to be missing in all the robot examples for instance Jackal:
https://github.com/clearpathrobotics/cpr-documentation/blob/development/docs_versioned_docs/version-ros1noetic/robots/outdoor_robots/jackal/tutorials_jackal.mdx#L504C13-L504C13

**Comment by hilary-luo** [comment]
@mhosmar-cpr Thank you for your input. We will not be taking your suggestion and here is why: Adding the `-r` parameter would change the operation such that the message would be published repeatedly. The tutorial here is to send a single command that will move the robot momentarily. Using the -r command to blindly drive with a certain trajectory can cause dangerous situations and thus we do not encourage that. (Note this is different than autonomous navigation which uses sensorization to prevent these dangerous situations.) If you are using that method please ensure that the system is being adequately supervised and that that motion can be stopped in a safe manner.
